### ISSUE TITLE
Improve login method with error validation

### ISSUE THREAD

**Issue by adeiming** [qirolab/nuxt-sanctum-authentication#7]
Why login method isn't as simple as the out-of-the-box useSanctumForm() with error validation?

**Comment by hkp22** [comment]
@adeiming 
Thank you for your question!  

The `login()` method in the `nuxt-sanctum-authentication` module is designed to provide more flexibility and customization options compared to the out-of-the-box `useSanctumForm()`. While `useSanctumForm()` is great for simple use cases and automatically handles form state and validation, the `login()` method provides:

- **Cookie/Token Authentication Support**: The `login()` method accommodates both cookie and token-based authentication, providing more versatility.  
- **Dynamic Response Handling**: It allows for custom response key extraction (e.g., handling APIs where the token or user data is nested under specific keys like `data.token`).  
- **Custom Headers or Configurations**: You can pass additional options, such as custom headers, through the `login()` method for advanced API requirements.

**Comment by adeiming** [comment]
I agree with that, but my question is, how do I make login() handle validation errors directly without having to create its own error handler like useSanctumForm()

**Comment by hkp22** [comment]
You can use the following for that:

```
<script setup lang="ts">
import { FetchError } from "ofetch";

const { login } = useSanctum();

const form = ref({
  email: "",
  password: "",
});

const busy = ref(false);
const errors = ref({});

const submitForm = async () => {
  try {
    errors.value = {};
    busy.value = true;

    await login(form.value);

  } catch (err) {
    busy.value = false;
    if (err instanceof FetchError && err.response?.status === 422) {
      errors.value = err.response._data.errors;
    }
  }
};
</script>
```

**Comment by adeiming** [comment]
Yep, that means it can't be like useSantumForm(), right? okay, thanks for the response. Maybe it could be a consideration for the next version
